/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Verifikasi proses aktif (liveness probe).
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Kesiapan layanan menerima beban trafik (readiness probe).
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/startup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Startup
         * @description Hasil pemeriksaan komprehensif 18 langkah Fail-Closed Startup Gate.
         */
        get: operations["health_startup_health_startup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil Konteks Tenant Terotentikasi
         * @description Mengembalikan konteks tenant yang telah divalidasi anti-spoofing
         *     beserta peran dan kapabilitas terdaftar.
         */
        get: operations["get_tenant_context_api_v1_tenant_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/company-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Company Code (Owner / Tenant Admin)
         * @description Membuat kode registrasi perusahaan baru (CSPRNG):
         *     - Plain-text kode hanya dikembalikan satu kali dalam respons API ini.
         *     - Hanya hash SHA-256 yang disimpan di database `tenant_company_codes`.
         */
        post: operations["create_company_code_api_v1_tenant_company_codes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/hr-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Antrean HR Approval (Owner / Admin / Manager)
         * @description Mengambil daftar calon staf yang mengajukan pendaftaran ke perusahaan.
         *     Dilindungi oleh PDP dengan kapabilitas `hr.approval.review`.
         */
        get: operations["list_hr_queue_api_v1_tenant_hr_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/hr-queue/{queue_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Antrean HR Approval (Approve / Reject Staf)
         * @description Menyetujui atau menolak pendaftaran staf:
         *     - Jika 'approved': buat `tenant_memberships` (role `STAFF_HUMAN`), update queue jadi 'approved', update use_count kode.
         *     - Jika 'rejected': update status queue menjadi 'rejected' beserta alasan penolakan.
         */
        post: operations["review_hr_queue_api_v1_tenant_hr_queue__queue_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/register-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrasi Tenant Baru (Self-Service Tenant Creation)
         * @description Mendaftarkan perusahaan/tenant baru secara mandiri:
         *     1. Mengatur konteks tenant baru via tenant_tx(new_tenant_id) untuk memenuhi kebijakan RLS.
         *     2. Membuat entri baru pada tabel `tenants`.
         *     3. Menghubungkan paket langganan awal (`subscription_plans`).
         *     4. Mendaftarkan user sebagai anggota pertama di `tenant_memberships`.
         *     5. Menetapkan role `TENANT_OWNER` di `user_roles`.
         *     6. Mencatat aksi di `audit_logs`.
         */
        post: operations["register_tenant_api_v1_onboarding_register_tenant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/join-company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validasi & Submit Registrasi Staf (via Company Code)
         * @description Calon staf mendaftar ke perusahaan menggunakan Company Code:
         *     1. Memvalidasi hash Company Code (aktif, belum kedaluwarsa, belum melampaui batas penggunaan).
         *     2. Menempatkan pendaftaran ke dalam `hr_approval_queue` dengan status 'pending'.
         *     3. Notifikasi in-app siap ditinjau oleh HR / Tenant Admin.
         */
        post: operations["join_company_api_v1_onboarding_join_company_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/permissions/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get AI Data Permission Matrix
         * @description Mengambil matriks izin data: baris AI Agent Personas, kolom Enterprise System Connections, sel access_level.
         */
        get: operations["get_permission_matrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/permissions/matrix/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update AI Data Permission Cell
         * @description Memperbarui atau mencabut izin akses sel per persona x konektor. Hanya untuk TENANT_OWNER / TENANT_ADMIN. Tercatat di Audit Ledger.
         */
        put: operations["update_permission_cell"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/permissions/evaluate-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Test AI Data Access PDP
         * @description Evaluasi uji otorisasi PDP langsung terhadap sumber data perusahaan. Default fail-closed: DENIED_NO_POLICY.
         */
        post: operations["evaluate_access_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/permissions/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Permission Audit Logs
         * @description Mengambil riwayat Audit Ledger khusus peristiwa izin data & evaluasi PDP.
         */
        get: operations["get_permission_audit_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/tokenopt/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Savings Summary
         * @description Mengambil metrik ringkasan penghematan token, persentase cache hit, dan perbandingan biaya.
         */
        get: operations["get_token_savings_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/tokenopt/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Savings Logs
         * @description Mengambil riwayat telemetri penghematan token dan audit cache hit/miss.
         */
        get: operations["get_token_savings_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/agent-catalog/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Agent Blueprint Package
         * @description Pipeline ingesti paket blueprint skill agen AI baru dengan validasi dan policy scanner.
         */
        post: operations["ingest_skill_package"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/agent-catalog/blueprints/{blueprint_id}/rollout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition Blueprint Rollout Stage
         * @description Mentransisikan status rollout blueprint (INTERNAL -> BETA_TENANT -> GENERAL_AVAILABILITY). Wajib lolos pemindai kebijakan ('PASSED').
         */
        post: operations["transition_rollout_stage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/agent-catalog/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Agent Blueprints
         * @description Mengambil katalog lengkap seluruh blueprint skill agen untuk Super Admin.
         */
        get: operations["list_all_blueprints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/agent-catalog/blueprints/{blueprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blueprint Detail
         * @description Mengambil detail satu blueprint agen berdasarkan ID atau package_id.
         */
        get: operations["get_blueprint_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/agent-catalog/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Available Blueprints For Tenant
         * @description Mengambil daftar blueprint yang dapat diakses oleh tenant (GA atau BETA yang diizinkan).
         */
        get: operations["list_available_for_tenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateCompanyCodeRequest */
        CreateCompanyCodeRequest: {
            /**
             * Expires In Days
             * @description Masa berlaku kode dalam hari
             * @default 30
             */
            expires_in_days: number;
            /**
             * Max Uses
             * @description Batas maksimum penggunaan (opsional)
             */
            max_uses?: number | null;
        };
        /** CreateCompanyCodeResponse */
        CreateCompanyCodeResponse: {
            /** Code */
            code: string;
            /** Expires At */
            expires_at: string | null;
            /** Max Uses */
            max_uses: number | null;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** HRQueueItemResponse */
        HRQueueItemResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Requesting Auth User Id */
            requesting_auth_user_id: string;
            /** Company Code Id */
            company_code_id: string | null;
            /** Submitted Profile */
            submitted_profile: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JoinCompanyRequest */
        JoinCompanyRequest: {
            /**
             * Company Code
             * @description Kode registrasi perusahaan
             */
            company_code: string;
            /**
             * Full Name
             * @description Nama lengkap calon staf
             */
            full_name: string;
            /**
             * Email
             * @description Email calon staf
             */
            email: string;
            /**
             * Auth User Id
             * @description ID user otentikasi Supabase
             */
            auth_user_id: string;
            /**
             * Department Id
             * @description ID departemen pilihan (opsional)
             */
            department_id?: string | null;
        };
        /** JoinCompanyResponse */
        JoinCompanyResponse: {
            /** Status */
            status: string;
            /** Queue Id */
            queue_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Message */
            message: string;
        };
        /** RegisterTenantRequest */
        RegisterTenantRequest: {
            /**
             * Legal Name
             * @description Nama hukum resmi perusahaan
             */
            legal_name: string;
            /**
             * Display Name
             * @description Nama tampilan tenant
             */
            display_name: string;
            /**
             * Owner Auth User Id
             * @description ID user otentikasi Supabase
             */
            owner_auth_user_id: string;
            /**
             * Owner Full Name
             * @description Nama lengkap pemilik/owner
             */
            owner_full_name: string;
            /**
             * Plan Code
             * @description Kode paket langganan
             * @default FREE_TRIAL
             */
            plan_code: string;
        };
        /** RegisterTenantResponse */
        RegisterTenantResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Legal Name */
            legal_name: string;
            /** Display Name */
            display_name: string;
            /** Status */
            status: string;
            /** Membership Id */
            membership_id: string;
            /** Role */
            role: string;
            /** Created At */
            created_at: string;
        };
        /** ReviewHRQueueRequest */
        ReviewHRQueueRequest: {
            /**
             * Decision
             * @description 'approved' atau 'rejected'
             */
            decision: string;
            /**
             * Rejection Reason
             * @description Alasan jika ditolak
             */
            rejection_reason?: string | null;
        };
        /** ReviewHRQueueResponse */
        ReviewHRQueueResponse: {
            /** Queue Id */
            queue_id: string;
            /** Status */
            status: string;
            /** Reviewed At */
            reviewed_at: string;
            /** Message */
            message: string;
        };
        /** StartupCheckResult */
        StartupCheckResult: {
            /** Step Number */
            step_number: number;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "not_implemented_yet";
            /** Detail */
            detail: string;
        };
        /** StartupGateReport */
        StartupGateReport: {
            /** Overall Passed */
            overall_passed: boolean;
            /** Total Steps */
            total_steps: number;
            /** Passed Steps */
            passed_steps: number;
            /** Failed Steps */
            failed_steps: number;
            /** Not Implemented Steps */
            not_implemented_steps: number;
            /** Checks */
            checks: components["schemas"]["StartupCheckResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_startup_health_startup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartupGateReport"];
                };
            };
        };
    };
    get_tenant_context_api_v1_tenant_context_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_code_api_v1_tenant_company_codes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCompanyCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hr_queue_api_v1_tenant_hr_queue_get: {
        parameters: {
            query?: {
                queue_status?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HRQueueItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_hr_queue_api_v1_tenant_hr_queue__queue_id__review_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Tenant-Id"?: string | null;
            };
            path: {
                queue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewHRQueueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewHRQueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_tenant_api_v1_onboarding_register_tenant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterTenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_company_api_v1_onboarding_join_company_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinCompanyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinCompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_permission_matrix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matriks izin data agen AI bertenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_permission_cell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hasil pembaruan sel matriks izin dan pencatatan audit. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    evaluate_access_test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keputusan ABAC PDP dan entri audit log nyata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_permission_audit_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar entri audit log izin data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_token_savings_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_token_savings_logs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ingest_skill_package: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    transition_rollout_stage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Policy Scan Required */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_blueprints: {
        parameters: {
            query?: {
                stage?: string;
                category?: string;
                policy_status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_blueprint_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_available_for_tenant: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
